/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 

package JoshA;


import org.springframework.boot.SpringApplication; 
import org.springframework.boot.autoconfigure.SpringBootApplication; 
import org.springframework.boot.builder.SpringApplicationBuilder; 
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import JoshA.DataBox.Fruit;

@SpringBootApplication 
public class Main extends SpringBootServletInitializer{
    
    
    public static void main(String[] args){
        
        SpringApplication.run(Main.class, args); 
    }
    
    @Override  protected SpringApplicationBuilder configure(SpringApplicationBuilder application){
        
        return application.sources(Main.class);
    }
}


//Make sure that Spring-REST-Build project which is the app that we will send request to is already running

//java -jar ./app/build/libs/app-ConsumeWeb-0.1.0.war